# Generated by Django 5.0.6 on 2025-05-19 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('famille', models.CharField(max_length=24)),
                ('classe', models.CharField(max_length=24)),
                ('type_gros', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20, unique=True)),
                ('adress', models.TextField(blank=True, default='', max_length=25)),
                ('contact', models.CharField(blank=True, default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=50)),
                ('provenance', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trosa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=25)),
                ('date', models.DateField(auto_now_add=True)),
                ('adress', models.TextField(blank=True)),
                ('contact', models.CharField(blank=True, max_length=20)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=10)),
                ('montant_restant', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('prix_total', models.DecimalField(decimal_places=0, max_digits=10)),
                ('prix_restant', models.DecimalField(decimal_places=0, max_digits=10)),
                ('client', models.CharField(blank=True, default='', max_length=20)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FilAttenteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('prix_total', models.DecimalField(decimal_places=0, max_digits=10)),
                ('prix_restant', models.DecimalField(decimal_places=0, max_digits=10)),
                ('client', models.CharField(blank=True, default='', max_length=20)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_gros', models.DecimalField(decimal_places=0, max_digits=10)),
                ('prix_gros_init', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10)),
                ('qte_gros', models.IntegerField(default=0, null=True)),
                ('date_peremption', models.DateField(blank=True, default=None)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('detail', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='stock.detail')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='stock.fournisseur')),
                ('marque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='stock.marque')),
            ],
        ),
        migrations.CreateModel(
            name='AjoutStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte_gros_transaction', models.IntegerField(default=0, null=True)),
                ('type_transaction', models.TextField(max_length=25)),
                ('prix_total', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('date', models.DateTimeField(auto_now=True)),
                ('prix_gros', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('gestionnaire', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='stock.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reglement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=10)),
                ('moyen_paiement', models.CharField(blank=True, default='Espèces', max_length=50)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='VenteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte_gros_transaction', models.IntegerField(default=0, null=True)),
                ('type_transaction', models.TextField(max_length=25)),
                ('prix_total', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('date', models.DateTimeField(auto_now=True)),
                ('facture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='stock.facture')),
                ('fil_attente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_related', to='stock.filattenteproduct')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='stock.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
