# Generated by Django 5.0.6 on 2025-05-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_remove_product_prix_gros_init'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prix_gros_achat',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10),
        ),
    ]
