# Generated by Django 5.0.6 on 2025-05-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_product_prix_gros_achat'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajoutstock',
            name='prix_gros_achat',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
