# Generated by Django 5.0.6 on 2025-05-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_ajoutstock_prix_gros_achat'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajoutstock',
            name='prix_vente',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venteproduct',
            name='prix_vente',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10),
        ),
    ]
