# Generated by Django 5.0.6 on 2025-05-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_ajoutstock_prix_vente_venteproduct_prix_vente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ajoutstock',
            name='prix_vente',
        ),
        migrations.AlterField(
            model_name='venteproduct',
            name='prix_vente',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10),
        ),
    ]
