# Generated by Django 5.0.6 on 2025-06-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_remove_ajoutstock_prix_vente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='demande_annulation',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='trosa',
            name='date_payement',
            field=models.DateField(blank=True, default=None),
        ),
    ]
