# Generated by Django 5.0.6 on 2025-06-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_facture_demande_annulation_trosa_date_payement'),
    ]

    operations = [
        migrations.AddField(
            model_name='venteproduct',
            name='date_payement',
            field=models.DateField(blank=True, default=None),
        ),
    ]
