# Generated by Django 5.0.6 on 2025-06-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_venteproduct_date_payement'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='montant_paye',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='facture',
            name='remarque',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='facture',
            name='prix_restant',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
