# Generated by Django 5.0.6 on 2025-06-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_facture_montant_paye_facture_remarque_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venteproduct',
            name='date_payement',
        ),
        migrations.AddField(
            model_name='facture',
            name='date_payement',
            field=models.DateField(blank=True, default=None),
        ),
    ]
