# Generated by Django 5.0.6 on 2025-06-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_remove_venteproduct_date_payement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='date_payement',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
