# Generated by Django 5.0.6 on 2025-06-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_alter_facture_date_payement'),
    ]

    operations = [
        migrations.AddField(
            model_name='filattenteproduct',
            name='date_payement',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='filattenteproduct',
            name='montant_paye',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='filattenteproduct',
            name='remarque',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
