# Generated by Django 5.0.6 on 2025-06-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_filattenteproduct_date_payement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trosa',
            name='adress',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='trosa',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
