# Generated by Django 5.0.6 on 2025-06-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_alter_trosa_adress_alter_trosa_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='ref_client',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
