# Generated by Django 5.0.6 on 2025-06-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_facture_ref_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='filattenteproduct',
            name='ref_client',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
