# Generated by Django 5.0.6 on 2025-06-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_filattenteproduct_ref_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='ref_client',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='filattenteproduct',
            name='ref_client',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
