# Generated by Django 5.0.6 on 2025-08-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0016_alter_facture_ref_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='client',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
